work_two_CSS = "li.np-hw-li:nth-child(3) > div:nth-child(2) > a:nth-child(3) > span:nth-child(1)"
people_num = "/html/body/div[2]/div/div/div/form/div/div[1]/div[2]/h2/span"
question_text1 = "//*[@id=\"questionContainer\"]/div/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[2]/div"
question_text2 = "//*[@id=\"questionContainer\"]/div/div[2]/div[3]/form/div/div[1]/div[2]/div[4]/div[2]/div"
question_file1 = "//*[@id=\"questionContainer\"]/div/div[2]/div[2]/div/div[1]/div[2]/div[4]/div[3]/a"
question_file2 = "//*[@id=\"questionContainer\"]/div/div[2]/div[3]/form/div/div[1]/div[2]/div[4]/div[3]/a"
question_1 = "//*[@id=\"questionContainer\"]/div/div[2]/div[2]/div/div[1]/div[2]/div[3]/div/input"
question_2 = "//*[@id=\"questionContainer\"]/div/div[2]/div[3]/form/div/div[1]/div[2]/div[3]/div/input"
